import "./globals.css";
import React from "react";
import { Inter } from "next/font/google";
import { UiContextProvider } from "@context/ui";
import { AuthProvider } from "@auth/libs/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <UiContextProvider>{children}</UiContextProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
