import Head from "next/head";
import { Header } from "@/components/common";
import { Hero, Swiper, Getstarted, Features } from "@/components/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Testimonial site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Hero />
        <Swiper />
        <Features />
        <Getstarted />
      </main>
    </>
  );
}
